---

  - name: Show OS family detected by Ansible
    debug:
      msg: "{{ ansible_facts['os_family'] }}"

  - name: Update packages on Debian Family
    apt:
      name: "*"
      state: latest
    when: ansible_facts['os_family'] == "Debian"

  - name: Update packages on RedHat family
    dnf:
      name: "*"
      state: latest
    when: ansible_facts['os_family'] == "RedHat"