---

  - name: Show OS family detected by Ansible
    debug:
      msg: "{{ ansible_facts['os_family'] }}"

  - name: Update packages on Debian Family
    apt:
      name: "*"
      state: latest
    when: ansible_facts['os_family'] == "Debian"

  - name: Update packages on RedHat family
    dnf:
      name: "*"
      state: latest
    when: ansible_facts['os_family'] == "RedHat"

  - name: Install httpd, php, mariadb and dependencies on Debian Family
    apt:
      name: "{{ item }}"
      state: present
    loop: 
      - apache2 
      - php 
      - libapache2-mod-php 
      - php-mysql 
      - mariadb-server 
      - wget 
      - unzip 
    when: ansible_facts['os_family'] == "Debian"

  - name: Install httpd, php, mariadb and dependencies on RedHat Family
    dnf:
      name: "{{ item }}"
      state: present
    loop: 
      - httpd 
      - php 
      # - libapache2-mod-php 
      # - php-mysql 
      - mariadb-server 
      - wget 
      - unzip 
    when: ansible_facts['os_family'] == "RedHat"

 
  - name: Start Apache2 and MariaDB on Debian Family
    service:
      name: "{{ item }}"
      state: started
    loop: 
      - apache2 
      - mariadb
    when: ansible_facts['os_family'] == "Debian"

